title: Jianxiang He
url: https://Jacksonha7.github.io/

owner:
  name: Jianxiang He
  avatar: jianxiang.jpg
  email: jhe307@connect.hkust-gz.edu.cn
  cv: https://Jacksonha7.com/file/CV-Hejianxiang.pdf
  github: Jacksonha7
  scholar: https://scholar.google.com.hk/citations?user=6ZJXY_EAAAAJ&hl=zh-CN
  xiaohongshu: https://xhslink.com/m/64BfDOv50hk
  zhihu: https://www.zhihu.com/people/he-jian-xiang-10
  bilibili: https://space.bilibili.com/51103812?spm_id_from=333.1189.0.0

links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Awards
    url: /awards/
  - title: Another Me
    url: /another-person/

timezone: China/Guangzhou
future: true
highlighter: rouge


permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

disqus:
  shortname: lancecai

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]
